/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package menader;

import static org.junit.Assert.*;

import org.junit.Test;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {}
}
